run:
  timeout: 1m
  modules-download-mode: readonly
  issues-exit-code: 1
  tests: true
  go: "1.18"

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - contextcheck
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exportloopref
    - gocritic
    - godot
    - gofmt
    - gofumpt
    - goimports
    - gomoddirectives
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - misspell
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - reassign
#    - revive
    - staticcheck
#    - stylecheck
    - tagliatelle
    - tenv
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars

  disable:
    - containedctx
    - cyclop
    - deadcode
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - errchkjson
    - execinquery
    - exhaustive
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - godox
    - goerr113
    - goheader
    - golint
    - gomodguard
    - goprintffuncname
    - grouper
    - ifshort
    - importas
    - interfacebloat
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - maligned
    - musttag
    - nestif
    - nlreturn
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - testpackage
    - typecheck
    - varnamelen
    - whitespace
    - wrapcheck
    - wsl
    - gomnd

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false

  exclude-rules:
    - path: 'httpr\.go'
      linters:
        - gosec